#!/usr/bin/perl -w
# script name: get_gff_refGene.pl
# script version: perl5.8.8.822
# Date: 2009.5.24
# Author: Swimbaby
# Description:
# Revision History:
# 1.0/<date>: original version
use File::Copy;
use strict;

#use Cwd;
#$mydir = getcwd();

##################################################
#输入名称
my $chrom = 'Negative';
# $filename = "";
##################################################
#主函数

while(my $filename = <*.txt>)
{
 chop $filename; chop $filename;  chop $filename;    chop $filename;
&get_sub_list($filename,$chrom);
 }
 print "complete!\n";


sub get_sub_list
{

open (TOTAL, "$_[0].txt") or die "error(input2):$!";
# 打开文件，准备从文件中读取DNA序列。
open(CONTAIN, ">$_[0]\_$_[1]") or die "error (output1):$!";
my  $line;
while ( $line= <TOTAL> )
{
   if($line =~ /^FEATURES/)
   {
     print CONTAIN "$line";
     last;
   }
}

while ( $line= <TOTAL> )
{
      my @terms = split(/\t/,$line);
      if($terms[6])
      {
        my $name = substr($terms[6],0,8);
           if($name eq $_[1])
             {
               print CONTAIN "$line";
             }
   }
}

close TOTAL;
close CONTAIN;
print "successful!\n";
}